version: "3"
services:
  go-proxy-api:
    container_name: ${SERVICE_NAME}_proxy
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:${PORT}:${PORT}"
    env_file:
      - .env
    restart: unless-stopped
